name: Angular
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci 

      - name: Build Angular app
        run: npm run build --if-present

      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
